# Generated by Django 3.0.8 on 2020-07-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
